In [5]:
import numpy as np

In [7]:
zeros = np.zeros(3)

In [8]:
matrix_zeros = np.zeros([2,6])

In [9]:
matrix_zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
matrix_zeros = np.zeros((6,5))

In [16]:
matrix_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
matrix_zeros = np.zeros((7))

In [20]:
matrix_zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [21]:
len (matrix_zeros)

7

In [23]:
matrix_ones = np.ones(8)

In [24]:
len (matrix_ones)

8

In [25]:
matrix_ones

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
[np.ones([2])]

[array([1., 1.])]

In [39]:
matrix_empty = np.empty((1,2))

In [40]:
matrix_empty

array([[1., 1.]])

In [47]:
x=np.array([2,1])

In [48]:
x

array([2, 1])

In [56]:
np.array([[1,2,3,4,5],[5,4,3,2,1]])

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [72]:
y=(np.array([[1,2,3,4,5],[5,4,3,2,1]]))

In [81]:
A=y

In [82]:
A.transpose()

array([[1, 5],
       [2, 4],
       [3, 3],
       [4, 2],
       [5, 1]])

In [78]:
len(A)

5

In [185]:
y

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [86]:
X=np.array([[1,2,3],[3,2,1]])

In [92]:
X

array([[1, 2, 3],
       [3, 2, 1]])

In [104]:
X[0:,1]

array([2, 2])

In [108]:
X[0,1]+X[1,2]

3

In [119]:
X[:,1]

array([2, 2])

In [135]:
X[1:,0]

array([3])

In [137]:
np.array([2,1,3])+np.array([2,1,3])

array([4, 2, 6])

In [181]:
x = np.array([1,2,3])

In [155]:
x[1:3]

array([2, 3])

In [156]:
x

array([1, 2, 3])

In [157]:
3 in x

True

In [158]:
45 in x

False

In [188]:
x

array([1, 2, 3])

In [189]:
k=x

In [192]:
k.fill(9)

In [195]:
k = np.array([0,1,2])

In [196]:
x[k]

array([9, 9, 9])

In [197]:
x

array([9, 9, 9])

In [198]:
x[True]

array([[9, 9, 9]])

In [199]:
x

array([9, 9, 9])

In [200]:
k

array([0, 1, 2])

In [201]:
x>1

array([ True,  True,  True])

In [202]:
x>3

array([ True,  True,  True])

In [203]:
x<2

array([False, False, False])

In [204]:
x =np.array([1,5,3])

In [205]:
x>2

array([False,  True,  True])

In [207]:
x[k>1]

array([3])

In [213]:
a=k>1

In [214]:
x[a]

array([3])

In [215]:
a

array([False, False,  True])

In [218]:
x[([True,0,0])]

array([5, 1, 1])

In [219]:
x

array([1, 5, 3])

In [220]:
import math as m


In [222]:
m.log(10)

2.302585092994046

In [223]:
x

array([1, 5, 3])

In [225]:
np.logspace(1,2,17)

array([ 10.        ,  11.54781985,  13.33521432,  15.39926526,
        17.7827941 ,  20.53525026,  23.71373706,  27.38419634,
        31.6227766 ,  36.51741273,  42.16965034,  48.69675252,
        56.23413252,  64.93816316,  74.98942093,  86.59643234,
       100.        ])

In [226]:
x

array([1, 5, 3])

In [227]:
x.size

3

In [228]:
x.shape

(3,)

In [229]:
y

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [230]:
y.size

10

In [231]:
y.shape

(2, 5)

In [234]:
val= np.random.random(2)

In [235]:
np.any(val>.9)

False

In [236]:
np.all(val<=.1)

False

In [249]:
np.any(val>=0.1)

True

In [250]:
val

array([0.47002569, 0.04726592])

In [252]:
x=20
not np.any([x%i == 0 for i in range(2, x)]) 

False

In [254]:
np.multiply(x,val)

array([9.40051384, 0.9453185 ])

In [261]:
c=np.array([[2,1,5],[1,1,1]])

In [268]:
d=np.array([[1,2,3],[3,1,3]])

In [269]:
np.multiply(c,d)

array([[ 2,  2, 15],
       [ 3,  1,  3]])